import React,{useEffect,useRef,useState} from 'react';
import type {Citation} from '../types';
export function Reveal({children,className=''}:{children:React.ReactNode;className?:string}){const ref=useRef<HTMLDivElement>(null);const [shown,setShown]=useState(false);useEffect(()=>{if(!ref.current)return;const io=new IntersectionObserver(([e])=>{if(e.isIntersecting){setShown(true);io.disconnect()}},{threshold:.08});io.observe(ref.current);return()=>io.disconnect()},[]);return <div ref={ref} className={`reveal ${shown?'shown':''} ${className}`}>{children}</div>}
export function SectionHeader({eyebrow,title,action}:{eyebrow:string;title:string;action?:React.ReactNode}){return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action}</div>}
export function ReliabilityBadge({grade='C'}:{grade?:string}){const label:{[k:string]:string}={A:'Confirmed',B:'Reliable',C:'Unverified',D:'Rumour'};return <span className={`reliability grade-${grade.toLowerCase()}`} title={`Grade ${grade}: ${label[grade]||'Unrated'}`}>{grade}<i>{label[grade]||'Unrated'}</i></span>}
export function SourceCitation({source}:{source:Citation}){const title=source.title||source.document_title||'Source record';const meta=[source.source_type,source.page_number&&`Page ${source.page_number}`,source.reliability_grade&&`Grade ${source.reliability_grade}`].filter(Boolean).join(' · ');return <article className="citation"><div><strong>{title}</strong><small>{meta||'Supporting evidence'}</small></div>{source.url&&<a href={source.url} target="_blank" rel="noreferrer">Open ↗</a>}{source.snippet&&<p>{source.snippet}</p>}</article>}
export function EmptyState({title='No evidence in this range',detail='Try a wider date range or refresh after the next ingestion.'}:{title?:string;detail?:string}){return <div className="state empty"><span>◇</span><strong>{title}</strong><p>{detail}</p></div>}
export function ErrorState({retry}:{retry:()=>void}){return <div className="state error" role="alert"><span>!</span><strong>Intelligence service unavailable</strong><p>The dashboard could not reach the API. Existing data has not been replaced with estimates.</p><button onClick={retry}>Try again</button></div>}
export function LoadingSkeleton(){return <main className="page-shell skeleton-page" aria-busy="true"><div className="sk sk-title"/><div className="sk-grid">{Array.from({length:6},(_,i)=><div className="sk sk-card" key={i}/>)}</div><div className="sk-grid two"><div className="sk sk-chart"/><div className="sk sk-chart"/></div></main>}
